### ISSUE TITLE
recive for CentOS?

### ISSUE THREAD

**Issue by timiil** [bebehei/pixieboot#2]
Hi,  very great project.
will be very nice to have recipe for CentOS :)

**Comment by bebehei** [comment]
I'm not familiar with CentOS and I'm not able to add support for it.

If you want to do it, feel free to open a PR. I will merge it.

**Comment by bebehei** [comment]
look into the [`recipes`-folder](https://github.com/bebehei/pixieboot/tree/master/recipes), copy an existing one and adapt it. If CentOS/yum has got something similar to Debian's `debootstrap`, the job will be quite easy.
